import logging.handlers
from _typeshed import Incomplete
from typing import Any

class GzipRotatingFileHandler(logging.handlers.RotatingFileHandler):
    stream: Incomplete
    def doRollover(self) -> None: ...

class Logger:
    name: Incomplete
    log_level: Incomplete
    max_bytes: Incomplete
    backup_count: Incomplete
    log_dir: Incomplete
    log_file: Incomplete
    logger: Incomplete
    def __init__(self, name: str = 'app', log_level: int = ..., log_dir: str | None = None, max_bytes: int = ..., backup_count: int = 5, db_settings: _ResolvedSettingsDict | None = None) -> None: ...
    def info(self, message: str, extra: dict[str, Any] | None = None) -> None: ...
    def warning(self, message: str, extra: dict[str, Any] | None = None) -> None: ...
    def error(self, message: str, extra: dict[str, Any] | None = None) -> None: ...
    async def ainfo(self, message: str, extra: dict[str, Any] | None = None) -> None: ...
    async def awarning(self, message: str, extra: dict[str, Any] | None = None) -> None: ...
    async def aerror(self, message: str, extra: dict[str, Any] | None = None) -> None: ...

def setup_logger(name: str = 'app', log_level: int = ..., log_dir: str | None = None, db_settings: _ResolvedSettingsDict | None = None) -> Logger: ...
async def query_logs(query: str, db_settings: _ResolvedSettingsDict, params: list[Any] | None = None) -> list[dict[str, Any]]: ...
get_logger = setup_logger
